- Infrastructure:
    - Portainer:
        icon: simple-icons:portainer
        href: http://portainer.home
        description: Container Management
        status: http://portainer.home
    - Nginx Proxy Manager:
        icon: simple-icons:nginx
        href: http://npm.home:81
        description: Reverse Proxy Management
        status: http://npm.home:81
- Network:
    - AdGuard Home:
        icon: simple-icons:adguard
        href: http://adguard.home:3000
        description: DNS Ad Blocking & Management
        status: http://adguard.home:3000